### ISSUE TITLE
Not Working with All files

### ISSUE THREAD

**Issue by Baxter92** [KasemJaffer/receive_sharing_intent#212]
Cannot listen txt or pdf files

**Comment by simonbengtsson** [comment]
Likely related to files not working right now. A fix is available here https://github.com/KasemJaffer/receive_sharing_intent/pull/201. You can use it like this in your pubspec.yaml.

```yaml
receive_sharing_intent:
  git:
    url: https://github.com/reynirf/receive_sharing_intent
    ref: patch-1
```

**Comment by ArjunBhilare** [comment]
@Baxter92 Did you resolve this? I am facing the same issue. 
@simonbengtsson  I have added your solution but still facing the same issue.
Any solution?

**Comment by simonbengtsson** [comment]
I believe so. Unsure exactly how but you can take a look at the app code if it helps

https://github.com/simonbengtsson/airdash
